# Generated by Django 5.0.4 on 2026-01-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Book name (e.g., 'John')", max_length=50)),
                ('slug', models.SlugField(help_text="URL-friendly name (e.g., 'john')", unique=True)),
                ('order', models.PositiveIntegerField(help_text='Book order (1-66)', unique=True)),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2)),
                ('chapters', models.PositiveIntegerField(default=1, help_text='Number of chapters in book')),
            ],
            options={
                'verbose_name': 'Bible Book',
                'verbose_name_plural': 'Bible Books',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField()),
                ('verse', models.PositiveIntegerField()),
                ('text', models.TextField(help_text='Full verse text')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblebook')),
            ],
            options={
                'verbose_name': 'Bible Verse',
                'verbose_name_plural': 'Bible Verses',
                'ordering': ['book__order', 'chapter', 'verse'],
                'indexes': [models.Index(fields=['book', 'chapter'], name='bible_bible_book_id_287370_idx')],
                'unique_together': {('book', 'chapter', 'verse')},
            },
        ),
    ]
