# Generated by Django 4.0.6 on 2022-08-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="PrayerGroup",
        ),
    ]
