# Generated by Django 4.0.6 on 2022-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0002_rename_group_prayergroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayergroup",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
