# Generated by Django 4.0.6 on 2022-08-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0003_alter_prayergroup_long_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
