# Generated by Django 5.0.4 on 2026-04-24 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0010_add_smslog_and_message_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundSmsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="twilio", max_length=30)),
                ("provider_message_id", models.CharField(max_length=64, unique=True)),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("body", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("direction", models.CharField(default="inbound", max_length=20)),
                ("processed", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_sms_messages",
                        to="prayer.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
