# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0011_inboundsmsmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayermessage",
            name="direct_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="One-off contacts this message is targeted to",
                related_name="direct_messages",
                to="prayer.person",
            ),
        ),
    ]
