# Generated by Django 5.0.4 on 2026-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0011_inboundsmsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates this person as a Prayer Group admin who receives inbound SMS notifications'),
        ),
    ]
