# Generated by Django 5.0.4 on 2026-07-17 04:03

from django.conf import settings
from django.db import migrations, models


def _normalized_name(first_name, last_name):
    return " ".join(f"{first_name or ''} {last_name or ''}".casefold().split())


def link_people_to_users_by_unique_name(apps, schema_editor):
    """Perform the approved one-time exact-name association rollout."""
    Person = apps.get_model("prayer", "Person")
    User = apps.get_model("auth", "User")

    users_by_name = {}
    for user in User.objects.filter(prayer_person__isnull=True):
        normalized_name = _normalized_name(user.first_name, user.last_name)
        if normalized_name:
            users_by_name.setdefault(normalized_name, []).append(user.pk)

    people_by_name = {}
    for person in Person.objects.filter(user__isnull=True):
        normalized_name = _normalized_name(person.first_name, person.last_name)
        if normalized_name:
            people_by_name.setdefault(normalized_name, []).append(person.pk)

    for normalized_name, person_ids in people_by_name.items():
        user_ids = users_by_name.get(normalized_name, [])
        if len(person_ids) == 1 and len(user_ids) == 1:
            Person.objects.filter(pk=person_ids[0], user__isnull=True).update(
                user_id=user_ids[0]
            )


def preserve_processed_messages_as_read(apps, schema_editor):
    """Keep legacy processed messages read for current managers and staff."""
    InboundSmsMessage = apps.get_model("prayer", "InboundSmsMessage")
    User = apps.get_model("auth", "User")

    eligible_user_ids = set(
        User.objects.filter(is_staff=True).values_list("pk", flat=True)
    )
    eligible_user_ids.update(
        User.objects.filter(groups__name="Prayer Manager").values_list(
            "pk", flat=True
        )
    )
    if not eligible_user_ids:
        return

    through_model = InboundSmsMessage.read_by.through
    read_rows = [
        through_model(inboundsmsmessage_id=message_id, user_id=user_id)
        for message_id in InboundSmsMessage.objects.filter(
            processed=True
        ).values_list("pk", flat=True)
        for user_id in eligible_user_ids
    ]
    through_model.objects.bulk_create(read_rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0013_person_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundsmsmessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Prayer administrators who have marked this message as read."
                ),
                related_name="read_inbound_sms_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="notify_on_inbound_sms",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Send an SMS alert when a new inbound Prayer message arrives."
                ),
            ),
        ),
        migrations.RunPython(
            link_people_to_users_by_unique_name,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            preserve_processed_messages_as_read,
            migrations.RunPython.noop,
        ),
    ]
