# Generated by Django 5.0.4 on 2026-01-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediaformat",
            options={"ordering": ["name"]},
        ),
    ]
