# Generated by Django 5.0.4 on 2026-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a photo hosted elsewhere (e.g., Flickr, Google Photos). Leave blank if uploading locally.",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a local image (or provide an external URL below)",
                null=True,
                upload_to="photos/",
            ),
        ),
    ]
