# Generated by Django 5.0.4 on 2026-02-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0002_photo_external_url_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoessay",
            name="layout",
            field=models.CharField(
                choices=[
                    ("sequential_large", "Sequential - Large Photos (1 per row)"),
                    ("sequential_medium", "Sequential - Medium Photos (2 per row)"),
                    ("sequential_small", "Sequential - Small Photos (3 per row)"),
                    ("masonry", "Masonry Grid"),
                    ("collage_mixed", "Collage - Mixed Sizes"),
                ],
                default="sequential_medium",
                help_text="Choose how photos are displayed in this essay",
                max_length=20,
            ),
        ),
    ]
