# Generated by Django 5.0.4 on 2026-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0003_photoessay_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoessay",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured essays appear on the photography dashboard",
            ),
        ),
    ]
