# Generated by Django 5.0.4 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0004_photoessay_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoessay",
            name="show_essay_title",
            field=models.BooleanField(
                default=True,
                help_text="Show the essay title header on the detail page",
            ),
        ),
        migrations.AddField(
            model_name="photoessay",
            name="show_photo_titles",
            field=models.BooleanField(
                default=True,
                help_text="Show photo titles and captions inside the essay",
            ),
        ),
    ]
