# Generated by Django 5.0.4 on 2026-02-09 00:00

from django.db import migrations, models


def forwards_migrate_photo_links(apps, schema_editor):
    Photo = apps.get_model("photography", "Photo")
    PhotoEssayPhoto = apps.get_model("photography", "PhotoEssayPhoto")

    for photo in Photo.objects.exclude(essay__isnull=True):
        PhotoEssayPhoto.objects.create(
            essay_id=photo.essay_id,
            photo_id=photo.id,
            display_order=photo.display_order,
        )


def backwards_migrate_photo_links(apps, schema_editor):
    Photo = apps.get_model("photography", "Photo")
    PhotoEssayPhoto = apps.get_model("photography", "PhotoEssayPhoto")

    for photo in Photo.objects.all():
        link = (
            PhotoEssayPhoto.objects.filter(photo_id=photo.id)
            .order_by("display_order")
            .first()
        )
        if link:
            photo.essay_id = link.essay_id
            photo.display_order = link.display_order
        else:
            photo.essay_id = None
            photo.display_order = 0
        photo.save(update_fields=["essay", "display_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0005_photoessay_display_toggles"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoEssayPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order to display photos within this essay",
                    ),
                ),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="photo_links",
                        to="photography.photoessay",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="essay_links",
                        to="photography.photo",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "photo__created_at"],
                "unique_together": {("essay", "photo")},
            },
        ),
        migrations.AddField(
            model_name="photoessay",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="essays",
                through="photography.PhotoEssayPhoto",
                to="photography.photo",
            ),
        ),
        migrations.RunPython(
            forwards_migrate_photo_links, backwards_migrate_photo_links
        ),
        migrations.RemoveField(
            model_name="photo",
            name="essay",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="display_order",
        ),
    ]
