# Generated by Django 5.0.4 on 2026-02-09 00:00

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0006_photoessayphoto_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery_covers/"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow public access without a password",
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128)),
                (
                    "access_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("download_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order to display photos within this gallery",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_links",
                        to="photography.gallery",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_links",
                        to="photography.photo",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "photo__created_at"],
                "unique_together": {("gallery", "photo")},
            },
        ),
        migrations.CreateModel(
            name="GallerySelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="photography.gallery",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_selections",
                        to="photography.photo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("gallery", "photo", "session_key")},
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="galleries",
                through="photography.GalleryPhoto",
                to="photography.photo",
            ),
        ),
    ]
