# Generated by Django 4.0.4 on 2022-04-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fs2020", "0002_aircraft_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"verbose_name_plural": "Aircraft"},
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tied Down", "Tied Down"),
                    ("Pre-Flight", "Pre-Flight"),
                    ("In Flight", "In Flight"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rules",
                    models.CharField(
                        choices=[("VFR", "VFR"), ("IFR", "IFR")], max_length=100
                    ),
                ),
                ("icao_origin", models.CharField(max_length=10)),
                ("departure_datetime", models.DateTimeField()),
                ("altitude", models.IntegerField()),
                ("route", models.TextField()),
                ("icao_destination", models.CharField(max_length=10)),
                (
                    "n_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fs2020.aircraft",
                    ),
                ),
            ],
        ),
    ]
