# Generated by Django 5.0.4 on 2026-07-11 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_title', models.CharField(max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=255)),
                ('first_line', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('meter', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('copyright_status', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['canonical_title'],
            },
        ),
        migrations.CreateModel(
            name='Hymnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('denomination', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['title', 'publication_year'],
            },
        ),
        migrations.CreateModel(
            name='ScriptureReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meter', models.CharField(blank=True, max_length=100)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HymnImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='hymnary', max_length=50)),
                ('hymnal_code', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HymnalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title_as_printed', models.CharField(max_length=255)),
                ('first_line_as_printed', models.CharField(blank=True, max_length=500)),
                ('tune_as_printed', models.CharField(blank=True, max_length=255)),
                ('meter_as_printed', models.CharField(blank=True, max_length=100)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('publication_date', models.CharField(blank=True, max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('hymn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='hymns.hymn')),
                ('hymnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hymns.hymnal')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='hymns.hymnimportbatch')),
                ('scripture_references', models.ManyToManyField(blank=True, to='hymns.scripturereference')),
                ('topics', models.ManyToManyField(blank=True, to='hymns.topic')),
            ],
            options={
                'ordering': ['hymnal__title', 'number'],
            },
        ),
        migrations.CreateModel(
            name='HymnImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='hymns.hymnimportbatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='hymn',
            name='scripture_references',
            field=models.ManyToManyField(blank=True, to='hymns.scripturereference'),
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HymnUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hymnal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='hymns.hymnalentry')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hymns.serviceplan')),
            ],
            options={
                'ordering': ['-used_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('hymnal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='hymns.hymnalentry')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hymns.serviceplan')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='hymn',
            name='topics',
            field=models.ManyToManyField(blank=True, to='hymns.topic'),
        ),
        migrations.AddConstraint(
            model_name='tune',
            constraint=models.UniqueConstraint(fields=('name', 'meter'), name='unique_tune_name_meter'),
        ),
        migrations.AddField(
            model_name='hymnalentry',
            name='tune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='hymns.tune'),
        ),
        migrations.AddConstraint(
            model_name='hymnusage',
            constraint=models.UniqueConstraint(fields=('hymnal_entry', 'service_plan'), name='unique_usage_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='hymn',
            constraint=models.UniqueConstraint(fields=('normalized_title', 'first_line', 'author'), name='unique_hymn_identity'),
        ),
        migrations.AddConstraint(
            model_name='hymnalentry',
            constraint=models.UniqueConstraint(fields=('hymnal', 'number'), name='unique_hymnal_number'),
        ),
    ]
