# Generated by Django 4.0.4 on 2022-07-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douglas', '0003_league_driver_league_race_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='league',
            field=models.ManyToManyField(to='douglas.league'),
        ),
    ]
