# Generated by Django 4.0.4 on 2022-04-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
