# Generated by Django 4.0.4 on 2022-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_job_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='aviation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
