# Generated by Django 4.0.4 on 2022-07-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='field',
            field=models.CharField(choices=[('AVIA', 'Aviation'), ('TECH', 'Technology')], default='AVIA', max_length=4),
        ),
    ]
