# Generated by Django 4.0.6 on 2022-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_certification_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
