# Generated by Django 4.0.6 on 2022-07-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
    ]
